import type { AuditEvent, CheckoutAttempt } from "./types";

export const checkoutAttempts: CheckoutAttempt[] = [
  {
    id: "shopping-agent-04",
    agent: "ShoppingAgent 04",
    buyer: "Alex Kim",
    purchase: "Skincare bundle",
    amountLabel: "$42",
    merchant: "GlowHaus",
    paymentMethod: "Visa ending 4242",
    time: "2m ago",
    humanOwner: "Alex Kim",
    identityStatus: "Verified buyer and agent consent",
    allowedTypes: ["Retail checkout", "Wallet autofill", "Recurring skincare"],
    consentExpiration: "18 days",
    lastCheckoutAction: "Approved GlowHaus refill, 11 days ago",
    merchantPermissions: ["Health and beauty", "Subscriptions under $100"],
    baseline: "$35 to $90",
    signalLabels: [
      "Known buyer",
      "Known shipping address",
      "Low cart value",
      "Normal purchase behavior",
      "Agent permission valid",
    ],
    signals: {
      amount: 42,
      newDevice: false,
      newShippingAddress: false,
      billingShippingMismatch: false,
      merchantRisk: 31,
      agentPermissionLimit: 100,
      buyerHistory: "known",
      chargebackProbability: 20,
      velocityRisk: 14,
      paymentMethodTrust: 62,
      cartCategoryRisk: 18,
    },
  },
  {
    id: "giftfinder-12",
    agent: "GiftFinder 12",
    buyer: "Sarah Johnson",
    purchase: "Electronics bundle",
    amountLabel: "$1,250",
    merchant: "TechSquare",
    paymentMethod: "Mastercard ending 1199",
    time: "7m ago",
    humanOwner: "Sarah Johnson",
    identityStatus: "Verified identity, new session",
    allowedTypes: ["Gifts", "Consumer electronics", "One-time purchases"],
    consentExpiration: "9 days",
    lastCheckoutAction: "Gift search completed, 34m ago",
    merchantPermissions: ["Electronics up to $1,500", "No gift cards"],
    baseline: "$120 to $420",
    signalLabels: [
      "New device",
      "New shipping address",
      "Higher than normal spend",
      "Cart contains resellable goods",
      "Permission valid but above typical range",
    ],
    signals: {
      amount: 1250,
      newDevice: true,
      newShippingAddress: true,
      billingShippingMismatch: false,
      merchantRisk: 30,
      agentPermissionLimit: 1500,
      buyerHistory: "known",
      chargebackProbability: 35,
      velocityRisk: 38,
      paymentMethodTrust: 68,
      cartCategoryRisk: 66,
    },
  },
  {
    id: "luxuryscout-09",
    agent: "LuxuryScout 09",
    buyer: "Michael Chen",
    purchase: "Luxury watch",
    amountLabel: "$3,900",
    merchant: "PrimeTime Watches",
    paymentMethod: "Amex ending 5566",
    time: "12m ago",
    humanOwner: "Michael Chen",
    identityStatus: "Identity verified, permission conflict",
    allowedTypes: ["Luxury research", "Price monitoring", "Saved carts only"],
    consentExpiration: "Pending renewal",
    lastCheckoutAction: "Created cart at new merchant, 9m ago",
    merchantPermissions: ["Luxury browsing", "No autonomous checkout"],
    baseline: "$80 to $650",
    signalLabels: [
      "Billing and shipping mismatch",
      "Suspicious velocity",
      "New merchant",
      "High chargeback risk",
      "Agent permission limit exceeded",
    ],
    signals: {
      amount: 3900,
      newDevice: true,
      newShippingAddress: true,
      billingShippingMismatch: true,
      merchantRisk: 77,
      agentPermissionLimit: 500,
      buyerHistory: "thin",
      chargebackProbability: 72,
      velocityRisk: 82,
      paymentMethodTrust: 58,
      cartCategoryRisk: 88,
    },
  },
];

export const kpis = [
  { label: "Total agent checkouts", value: "1,284", delta: "+18.4%" },
  { label: "Approved revenue", value: "$482,300", delta: "+12.1%" },
  { label: "Revenue protected", value: "$41,820", delta: "+9.8%" },
  { label: "Step up verifications", value: "39", delta: "-4.2%" },
  { label: "Blocked risk", value: "$28,600", delta: "+22.7%" },
  { label: "Chargeback risk reduced", value: "31%", delta: "+6.5%" },
];

export const guardrails = [
  ["Under $100", "Auto approve if low risk"],
  ["$100 to $1,000", "Approve if known buyer and trusted merchant"],
  ["$1,000 to $5,000", "Step up verification if risk is medium or high"],
  ["Over $5,000", "Manual review"],
  ["Billing mismatch", "Review"],
  ["Sanctions hit", "Block"],
  ["Permission limit exceeded", "Block or review"],
  ["High chargeback merchant", "Hold for review"],
];

export const revenueMetrics = [
  ["Blocked suspicious checkout", "$3,900"],
  ["Prevented likely chargebacks", "$12,400"],
  ["Step up recoveries", "$18,200"],
  ["False positive rate", "2.1%"],
  ["Approved trusted transactions", "94%"],
];

export const riskDistribution = [
  { name: "Low", value: 58, color: "#00d084" },
  { name: "Medium", value: 26, color: "#635bff" },
  { name: "High", value: 11, color: "#f59e0b" },
  { name: "Critical", value: 5, color: "#e11d48" },
];

export const decisionBreakdown = [
  { name: "Approved", value: 72, fill: "#00d084" },
  { name: "Step up", value: 16, fill: "#f59e0b" },
  { name: "Review", value: 8, fill: "#635bff" },
  { name: "Blocked", value: 4, fill: "#e11d48" },
];

export const baseAuditEvents: AuditEvent[] = [
  { label: "Agent initiated checkout", detail: "GiftFinder 12 assembled cart at TechSquare.", time: "10:24 AM" },
  { label: "Buyer identity checked", detail: "Sarah Johnson identity and cardholder profile matched.", time: "10:24 AM" },
  { label: "Payment method verified", detail: "Mastercard ending 1199 has strong authorization history.", time: "10:25 AM" },
  { label: "Risk score generated", detail: "CheckoutGuard calculated medium-high transaction risk.", time: "10:25 AM" },
  { label: "Guardrail policy evaluated", detail: "Amount entered the $1,000 to $5,000 verification policy.", time: "10:25 AM" },
  { label: "Decision issued", detail: "Step up verification recommended before authorization.", time: "10:26 AM" },
  { label: "Reviewer action logged", detail: "Risk team has the evidence packet ready.", time: "10:26 AM" },
];
